# Настройки сайта GitHub Pages
lang: ru
remote_theme: just-the-docs/just-the-docs
title: "УВБТ 2502"
description: "Единая база знаний по дисциплинам"
color_scheme: nil
search_enabled: true
logo:
aux_links:
  "Репозиторий на GitHub": "{{ site.github.repository_url }}"
aux_links_new_tab: true
footer_content: "Сайт автоматически собирается GitHub Pages."

# Структура навигации
just_the_docs:
  collections:
    default:
      output: true
